#!/bin/bash

if [ ! -t 0 ]
then
    echo "piping feature is not yet implemented!"
    exit
fi


repo=$1
command=$2
parameter=$3
# import local files
dir="$(cd $(dirname $0);pwd)"
local_dir="$dir/src"
source "$local_dir/variables.sh"
source "$local_dir/colors.sh"
source "$local_dir/helpers.sh"
source "$local_dir/error.sh"
source "$local_dir/editor.sh"
source "$local_dir/functions.sh"
source "$local_dir/functions.ls.sh"
source "$local_dir/functions.update.sh"
source "$local_dir/functions.precheck.sh"
source "$local_dir/functions.edit.sh"
source "$local_dir/functions.cat.sh"



if [ ! -d $repo ]
then 
    echo $repo does not exist! Please create it before usage
    exit
fi

# change directory to repo
cd $repo 



# if repository not initialized then notify
if [ "$command" != "init" ] && [ "$command" != "i" ]  && [ ! -d ".git" ]
then
    color $Red
    print "Repository not initialized yet!"
    color $Green
    print "please run :"
    color $Color_Off
    print  "    doc [init|i]"
    print 
    exit
fi

# commands

if [ $# -gt 0 ]
then
    if [ "$command" == "init" ] || [ "$command" == "i" ]
    then
        if [ -d ".git" ]
        then
            colori $Yellow
            echo "Already Initialized"
            verify_requirements
        else
            colori $UGreen
            echo "Initializing_repo :"
            colori $Red
            git init 
            verify_requirements
        fi
    elif [ "$command" == "add" ] || [ "$command" == "a" ]
    then
        add
    elif [ "$command" == "list-files" ] || [ "$command" == "ls" ]
    then
        list_info
    elif [ "$command" == "edit" ] || [ "$command" == "e" ]
    then
        if [ "$parameter" == "header" ]
        then
            edit $header_file
            updateREADME "Changed header."
        elif [ "$parameter" == "footer" ]
        then
            edit $footer_file
            updateREADME "Changed footer."

        elif [ "$parameter" == "" ]
        then
            colori $Red 
            printi "Invalid file name!\n"
        else
            # edit file with number
            editWithNumber $parameter
        fi
    elif [ "$command" == "cat" ] || [ "$command" == "c" ]
    then
        showFileWithNumber $parameter

    elif [ "$command" == "del" ] || [ "$command" == "d" ]
    then
        deleteWithNumber $parameter

    elif [ "$command" == "help" ] || [ "$command" == "h" ]
    then
        error
    else
        color $Red
        echo "Invalid parameters"
        error
    fi
    exit 0

else
    error
fi


color $Color_Off